### ISSUE TITLE
../waveform.c:4:10: fatal error: 'groove/groove.h' file not found

### ISSUE THREAD

**Issue by hems** [andrewrk/node-waveform#1]
@ Darwin 10.9
@ node.js 0.10.33

npm install --save wavform is yielding the following error:

```
> waveform@2.0.0 install /Users/hems/git/my_app/node_modules/waveform
> node-gyp rebuild

  CC(target) Release/obj.target/waveform/waveform.o
../waveform.c:4:10: fatal error: 'groove/groove.h' file not found
#include <groove/groove.h>
         ^
1 error generated.
make: *** [Release/obj.target/waveform/waveform.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hems/git/my_app/node_modules/waveform
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! waveform@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the waveform@2.0.0 install script.
npm ERR! This is most likely a problem with the waveform package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls waveform
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "--save" "waveform"
npm ERR! cwd /Users/hems/git/my_app
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
final/application [
```

**Comment by adius** [comment]
You should make libgroove a proper dependency in the package!
Is this possible?

**Comment by andrewrk** [comment]
libgroove is reasonably small and could be bundled with npm. But libav is huge and better off using the system installation. So you should install libgroove from the system package manager which can drag in the libav dependency and then the npm package can use that.

**Comment by Borisstoy** [comment]
@andrewrk , I am trying to get libgroove installed on Mac OS. I've made it through on my other machine (WSL), but can't find my way on Mac.

I could install **libpng** and **zlib**, but a simple `brew install libgroove` or `brew install libgroove-dev` does not work.

Any guidance ?

**EDIT**

I manually downloaded groove package and placed it in my `/usr/local/Cellar` the groove files (`encoder.h`, `groove.h`, `queue.h`), still without luck.

When running a `yarn install` on my project with waveform (node) installed, I get the following:

```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/waveform/waveform.o
../waveform.c:4:10: fatal error: 'groove/groove.h' file not found
#include <groove/groove.h>
```
